### ISSUE TITLE
Pre-requirement

### ISSUE THREAD

**Issue by zxymike93** [tuirgin/drracket-spacemacs-theme#1]
Hi, I really like your work. I've been using ``base16`` for about a year.
I tried ``spacemacs-schemes`` on my new computer, and realized that ``base16`` might be an pre-requirement of this repo.
I'm not sure it's true.

**Comment by tuirgin** [comment]
There are no pre-requirements. The info.rkt defines everything and was created manually. Base-16 uses templates and scripts to generate schemes, but wasn't used for this.
