### ISSUE TITLE
Upload to pkg.racket-lang.org?

### ISSUE THREAD

**Issue by sorawee** [tuirgin/drracket-spacemacs-theme#2]
First of all, thanks for the theme! It looks really nice.

Would you mind uploading this package to pkg.racket-lang.org? This would make it possible to write `raco pkg install drracket-spacemacs-schemes`. Moreover, it will be listed in the directory, and if you tag the package with [`colorscheme`](https://pkgd.racket-lang.org/pkgn/search?tags=colorscheme), it would make it easier for people to discover your package.

Thanks!

**Comment by tuirgin** [comment]
I don't personally have a need for it as I've not been able to spend much time with Racket for the last couple years. Feel free to fork the repository and push it up to the racket servers. I'm more than happy for someone else to take it over.
